global:
  enabled: true

server:
  image: 
    repository: "hashicorp/vault-enterprise"
    tag: "1.6.0_ent"
    
  ha:
    enabled: true
    raft:
      enabled: true
 
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
      
        seal "azurekeyvault" {
          tenant_id       = "0e3e2e88-<add>"
          client_id       = "6adb5a84-<add>"
          client_secret   = "<<secret>>"
          vault_name      = "jlinn-vault-demo"
          key_name        = "jlinn-vault-unseal-key"
          subscription_id = "i14692f20-<<add>>"
        }

        storage "raft" {
          path = "/vault/data"
        }

  postStart:
  - "/bin/sh"
  - "-c"
  - "sleep 5 && cp /bootstrap.sh /tmp/bootstrap.sh && chmod +x /tmp/bootstrap.sh && /tmp/bootstrap.sh"
