global:
  enabled: true

server:
  image: 
    repository: "hashicorp/vault-enterprise"
    tag: "1.6.0_ent"
    
  ha:
    enabled: true
    raft:
      enabled: true
 
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
      
        seal "azurekeyvault" {
          tenant_id       = "0e3e2e88-8caf-41ca-b4da-e3b33b6c52ec"
          client_id       = "6adb5a84-8121-4837-81da-333400cb0e9d"
          client_secret   = "O4Rzw7F3wZg5go3gY71dAz~2-DiJ4r~sv_"
          vault_name      = "jlinn-vault-demo"
          key_name        = "jlinn-vault-unseal-key"
          subscription_id = "i14692f20-9428-451b-8298-102ed4e39c2a"
        }

        storage "raft" {
          path = "/vault/data"
        }

  postStart:
  - "/bin/sh"
  - "-c"
  - "sleep 5 && cp /bootstrap.sh /tmp/bootstrap.sh && chmod +x /tmp/bootstrap.sh && /tmp/bootstrap.sh"
